repos:
-   repo: https://github.com/psf/black
    rev: 23.11.0
    hooks:
    -   id: black
        language_version: python3
-   repo: https://github.com/PyCQA/pylint
    rev: v3.0.2
    hooks:
    -   id: pylint
        args: [--rcfile=.pylintrc]
